apiVersion: v1
kind: ConfigMap
data:
  ack-4.11-kube-1.25-api-removals-in-4.12: |-
      Kubernetes 1.25 and therefore OpenShift 4.12 remove several APIs which require admin consideration. Please see the knowledge article https://access.redhat.com/articles/6955381 for details and instructions.
metadata:
  name: admin-gates
  namespace: openshift-config-managed
  annotations:
    kubernetes.io/description: Define update gates for the administrator to acknowledge in the admin-acks ConfigMap in the openshift-config namespace.
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
